---
AWSTemplateFormatVersion: '2010-09-09'

Description: Partyfy your GIFs

Resources:

  PartyfiedBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 1
            Status: Enabled
      BucketName: !Sub "${AWS::AccountId}-${AWS::StackName}"
  #     NotificationConfiguration:
  #       LambdaConfigurations:
  #         - Function: !GetAtt PartyfyLambda.Arn
  #           Event: s3:ObjectCreated:*
  #           Filter:
  #             S3Key:
  #               Rules:
  #                 - Name: prefix
  #                   Value: "prepartyfy/"
  #
  # LambdaInvokePermission:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     FunctionName: !GetAtt PartyfyLambda.Arn
  #     Action: lambda:InvokeFunction
  #     Principal: s3.amazonaws.com
  #     SourceArn: !Sub arn:aws:s3:::${AWS::AccountId}-${AWS::StackName}

  # PartyfyLambda:
  #   Type: AWS::Lambda::Function
  #   Properties:
  #     Handler: lambda_function.lambda_handler
  #     Role: !GetAtt PartyfyLambdaRole.Arn
  #     Runtime: python3.7
  #     Code: ./partyfy
  #     Timeout: 60
  #
  # PartyfyLambdaRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     Path: /
  #     AssumeRolePolicyDocument:
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service: lambda.amazonaws.com
  #           Action: sts:AssumeRole
  #     ManagedPolicyArns:
  #       - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  ##########################################
  #       - !Ref PartyfiedBucketAccessPolicy
  #
  #
  # PartyfiedBucketAccessPolicy:
  #   Type: AWS::IAM::ManagedPolicy
  #   Properties:
  #     Description: >-
  #       Allow access to put and get from the Partyfied Bucket
  #     PolicyDocument:
  #       Version: 2012-10-17
  #       Statement:
  #         - Effect: Allow
  #           Action:
  #             - s3:ListBucket
  #           Resource: !Sub arn:aws:s3:::${AWS::AccountId}-${AWS::StackName}
  #         - Effect: Allow
  #           Action:
  #             - s3:GetObject
  #             - s3:PutObject
  #           Resource: !Sub arn:aws:s3:::${AWS::AccountId}-${AWS::StackName}/*



# Outputs:
#   BucketName:
#     Value: !Ref PartyfiedBucket
